# Generated by Django 3.1.4 on 2020-12-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_obj', models.JSONField(default=dict)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
