# Generated by Django 3.1.4 on 2020-12-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_collage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collage',
            name='list_obj',
            field=models.TextField(),
        ),
    ]
