# Generated by Django 3.1.4 on 2020-12-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20201222_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collage',
            name='list_obj',
            field=models.JSONField(),
        ),
    ]
